name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: Windows, python: '3.14', os: windows-latest}
          - {name: Windows ARM64, python: '3.14', os: windows-11-arm}
          - {name: Mac, python: '3.14', os: macos-latest}
          - {name: '3.14', python: '3.14', os: ubuntu-latest}
          - {name: '3.13', python: '3.13', os: ubuntu-latest}
          - {name: '3.12', python: '3.12', os: ubuntu-latest}
          - {name: '3.11', python: '3.11', os: ubuntu-latest}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Install uv
        uses: astral-sh/setup-uv@v10.2.0
        with:
          python-version: ${{ matrix.python }}
          enable-cache: true
      - name: Install project and dependencies
        run: uv sync --extra dev
      - name: Run tests
        run: uv run pytest
