from http.client import HTTPException

class HTTPParseError(HTTPException): ...

class HTTPResponseParser:
    def __init__(self) -> None: ...
    def feed(self, data: str | bytes, /) -> None: ...
    def get_code(self) -> int: ...
    def get_http_version(self) -> str: ...
    def get_remaining_content_length(self) -> int: ...
    def should_keep_alive(self) -> bool: ...
    def parser_failed(self) -> bool: ...
